export enum ControllerTextEnum {
  USER_GET_ALL_SUMMARY = 'Get all users with filtering, sorting, and search (Admin only)',
  USER_GET_BY_ID_SUMMARY = 'Get user by ID',
  USER_UPDATE_SUMMARY = 'Update user information',
  USER_CHANGE_PASSWORD_SUMMARY = 'Change user password',
  USER_UPDATE_ROLE_SUMMARY = 'Update user role (Admin only)',
  USER_DELETE_SUMMARY = 'Delete user',
  USER_UPDATE_STATUS_SUMMARY = 'Update user profile status',
  USER_UPDATE_IMAGE_SUMMARY = 'Update user profile image',

  USER_LIST_RETRIEVED_SUCCESS = 'List of users retrieved successfully',
  USER_RETRIEVED_SUCCESS = 'User retrieved successfully',
  USER_UPDATED_SUCCESS = 'User updated successfully',
  USER_PASSWORD_CHANGED_SUCCESS = 'Password changed successfully',
  USER_ROLE_UPDATED_SUCCESS = 'User role updated successfully',
  USER_DELETED_SUCCESS = 'User deleted successfully',
  USER_STATUS_UPDATED_SUCCESS = 'User profile status updated successfully',
  USER_IMAGE_UPDATED_SUCCESS = 'User profile image updated successfully',

  USER_UNAUTHORIZED = 'Unauthorized',
  USER_FORBIDDEN_ADMIN_REQUIRED = 'Forbidden - Admin role required',
  USER_NOT_FOUND = 'User not found',
  USER_INVALID_DATA = 'Invalid data',
  USER_INVALID_PASSWORD = 'Invalid password',
  USER_UNAUTHORIZED_INVALID_OLD_PASSWORD = 'Unauthorized or invalid old password',
  USER_INVALID_ROLE = 'Invalid role',
  USER_CANNOT_DELETE_OWN_ACCOUNT = 'Cannot delete own account',
  USER_CANNOT_DELETE_ADMIN_ACCOUNT = 'Cannot delete admin account',
  USER_INVALID_STATUS = 'Invalid status',
  USER_INVALID_IMAGE = 'Invalid image',

  USER_ID_PARAM_DESCRIPTION = 'User ID',

  AUTH_SIGNIN_SUMMARY = 'Sign in with email/phone and password',
  AUTH_SIGNUP_SUMMARY = 'Create a new user account',
  AUTH_SOCIAL_SUMMARY = 'Sign in with social provider (Google/Facebook)',
  AUTH_FORGOT_PASSWORD_SUMMARY = 'Forgot password',
  AUTH_RESET_PASSWORD_SUMMARY = 'Reset password',
  AUTH_REFRESH_TOKEN_SUMMARY = 'Refresh token',
  AUTH_VERIFY_USER_SUMMARY = 'Verify user',
  AUTH_UNLOCK_ACCOUNT_SUMMARY = 'Unlock a locked user account (Admin only)',

  AUTH_USER_SIGNED_IN_SUCCESS = 'User successfully signed in',
  AUTH_USER_CREATED_SUCCESS = 'User successfully created',
  AUTH_USER_SIGNED_UP_SUCCESS = 'User signed up successfully',
  AUTH_SOCIAL_AUTH_SUCCESS = 'User successfully authenticated with social provider',
  AUTH_PASSWORD_RESET_EMAIL_SENT = 'Password reset email sent successfully',
  AUTH_PASSWORD_RESET_SUCCESS = 'Password reset successfully',
  AUTH_TOKEN_REFRESHED_SUCCESS = 'Token refreshed successfully',
  AUTH_USER_VERIFIED_SUCCESS = 'User verified successfully',
  AUTH_ACCOUNT_UNLOCKED_SUCCESS = 'Account unlocked successfully',

  AUTH_INVALID_CREDENTIALS_OR_MISSING_FIELDS = 'Invalid credentials or missing fields',
  AUTH_INVALID_CREDENTIALS = 'Invalid credentials',
  AUTH_INVALID_DATA_OR_MISSING_FIELDS = 'Invalid data or missing required fields',
  AUTH_USER_ALREADY_EXISTS = 'User with this email/phone already exists',
  AUTH_INVALID_TOKEN_OR_UNSUPPORTED_PROVIDER = 'Invalid token or unsupported provider',
  AUTH_SOCIAL_AUTH_FAILED = 'Social authentication failed',
  AUTH_INVALID_EMAIL = 'Invalid email',
  AUTH_INVALID_TOKEN_OR_MISSING_FIELDS = 'Invalid token or missing fields',
  AUTH_USER_NOT_FOUND = 'User not found!',
  AUTH_UNAUTHORIZED = 'Unauthorized!',
  AUTH_FORBIDDEN_ADMIN_REQUIRED = 'Forbidden - Admin role required!',

  HEALTH_CHECK_SUMMARY = 'Check application health status',
  HEALTH_READINESS_SUMMARY = 'Check if application is ready to accept traffic',
  HEALTH_LIVENESS_SUMMARY = 'Check if application is alive',

  HEALTH_CHECK_SUCCESS = 'Health check successful',
  HEALTH_APPLICATION_READY = 'Application is ready',
  HEALTH_APPLICATION_ALIVE = 'Application is alive',

  HEALTH_SERVICE_UNAVAILABLE = 'Service unavailable',
  HEALTH_APPLICATION_NOT_READY = 'Application is not ready',

  CATEGORY_CREATE_SUMMARY = 'Create a new category',
  CATEGORY_GET_ALL_SUMMARY = 'Get all categories',
  CATEGORY_GET_BY_ID_SUMMARY = 'Get category by ID',
  CATEGORY_GET_BY_SLUG_SUMMARY = 'Get category by slug',
  CATEGORY_UPDATE_SUMMARY = 'Update category',
  CATEGORY_DELETE_SUMMARY = 'Delete category',

  CATEGORY_LIST_RETRIEVED_SUCCESS = 'List of categories retrieved successfully',
  CATEGORY_RETRIEVED_SUCCESS = 'Category retrieved successfully',
  CATEGORY_CREATED_SUCCESS = 'Category created successfully',
}
