const MINUTES_TO_SECONDS = 60;
const SECONDS_TO_MILLISECONDS = 1000;

export const MAX_FAILED_LOGIN_ATTEMPTS = 5;
export const ACCOUNT_LOCKOUT_DURATION_MINUTES = 15;
export const ACCOUNT_LOCKOUT_DURATION_MS =
  ACCOUNT_LOCKOUT_DURATION_MINUTES *
  MINUTES_TO_SECONDS *
  SECONDS_TO_MILLISECONDS;
