export const DATABASE_CONSTANTS = {
  DEFAULT_MAX_POOL_SIZE: 10,
  DEFAULT_MIN_POOL_SIZE: 2,
  DEFAULT_MAX_IDLE_TIME_MS: 60000,
  DEFAULT_WAIT_QUEUE_TIMEOUT_MS: 10000,
  DEFAULT_SERVER_SELECTION_TIMEOUT_MS: 10000,
  DEFAULT_SOCKET_TIMEOUT_MS: 45000,
  DEFAULT_CONNECT_TIMEOUT_MS: 10000,
  RADIX: 10,
  RETRY_ATTEMPTS: 5,
  RETRY_DELAY: 3000,
  MAX_RECONNECT_ATTEMPTS: 10,
  RECONNECT_INTERVAL: 5000,
} as const;
