export const VALIDATION_CONSTANTS = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 50,

  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 20,

  PHONE_LENGTH: 11,
  PHONE_MIN_LENGTH: 10,
  PHONE_MAX_LENGTH: 15,

  ZIP_CODE_MAX_LENGTH: 10,
  ADDRESS_MAX_LENGTH: 200,
  CITY_MAX_LENGTH: 100,
  STATE_MAX_LENGTH: 100,
  COUNTRY_MAX_LENGTH: 100,

  URL_MIN_LENGTH: 2,
} as const;
